name: '< name >'
prediction_file: '<path to prediction results json file in coco format>'
prediction_label: '<optional display title for the first prediction results>'
prediction_file2: '<optional path to a second prediction results json file in coco format>'
prediction_label2: '<optional display title for the second prediction results>'
annotation_file: '<path to annotation json file in coco format>'
image_dir: '<path to image directory>'

output_dir: '<path to the directory where the outputs are to be saved>'
